[packaging] Update to upstream release 1.8.20p2. Contribute to JB#39090

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,5 +1,5 @@
 #
-# Copyright (c) 2010-2014 Todd C. Miller <Todd.Miller@courtesan.com>
+# Copyright (c) 2010-2015 Todd C. Miller <Todd.Miller@courtesan.com>
 #
 # Permission to use, copy, modify, and distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -31,6 +31,7 @@ includedir = @includedir@
 datarootdir = @datarootdir@
 localedir = @localedir@
 localstatedir = @localstatedir@
+exampledir = @exampledir@
 docdir = @docdir@
 mandir = @mandir@
 rundir = @rundir@
@@ -47,8 +48,8 @@ sudoers_gid = @SUDOERS_GID@
 sudoers_mode = @SUDOERS_MODE@
 shlib_mode = @SHLIB_MODE@
 
-SUBDIRS = compat common @ZLIB_SRC@ plugins/group_file plugins/sudoers \
-	  plugins/system_group src include doc
+SUBDIRS = lib/util @ZLIB_SRC@ plugins/group_file plugins/sudoers \
+	  plugins/system_group src include doc examples
 
 SAMPLES = plugins/sample
 
@@ -59,28 +60,34 @@ LIBTOOL_DEPS = @LIBTOOL_DEPS@
 
 SHELL = @SHELL@
 
+SED = @SED@
+
 INSTALL = $(SHELL) $(top_srcdir)/install-sh -c
+INSTALL_OWNER = -o $(install_uid) -g $(install_gid)
 
 ECHO_N = @ECHO_N@
 ECHO_C = @ECHO_C@
 
 # Message catalog support
 NLS = @SUDO_NLS@
-POTFILES = src/po/sudo.pot plugins/sudoers/po/sudoers.pot
+POTFILES = po/sudo.pot plugins/sudoers/po/sudoers.pot
 LOCALEDIR_SUFFIX = @LOCALEDIR_SUFFIX@
 MSGFMT = msgfmt
 MSGMERGE = msgmerge
 XGETTEXT = xgettext
 XGETTEXT_OPTS = -F -k_ -kN_ -kU_ --copyright-holder="Todd C. Miller" \
-		"--msgid-bugs-address=http://www.sudo.ws/bugs" \
+		"--msgid-bugs-address=https://bugzilla.sudo.ws" \
 		--package-name=@PACKAGE_NAME@ --package-version=$(VERSION) \
 		--flag warning:1:c-format --flag warningx:1:c-format \
 		--flag fatal:1:c-format --flag fatalx:1:c-format \
-		--flag easprintf:3:c-format --flag lbuf_append:2:c-format \
-		--flag lbuf_append_quoted:3:c-format --foreign-user
+		--flag easprintf:3:c-format --flag sudo_lbuf_append:2:c-format \
+		--flag sudo_lbuf_append_quoted:3:c-format --foreign-user
 
 # Default cppcheck options when run from the top-level Makefile
-CPPCHECK_OPTS = -q --force --enable=warning,performance,portability --suppress=constStatement --error-exitcode=1 --inline-suppr -U__cplusplus -UQUAD_MAX -UQUAD_MIN -UUQUAD_MAX -U_POSIX_HOST_NAME_MAX -U_POSIX_PATH_MAX
+CPPCHECK_OPTS = -q --force --enable=warning,performance,portability --suppress=constStatement --error-exitcode=1 --inline-suppr -Dva_copy=va_copy -U__cplusplus -UQUAD_MAX -UQUAD_MIN -UUQUAD_MAX -U_POSIX_HOST_NAME_MAX -U_POSIX_PATH_MAX -U__NBBY -DNSIG=64
+
+# Default splint options when run from the top-level Makefile
+SPLINT_OPTS = -D__restrict= -checks
 
 all: config.status
 	for d in $(SUBDIRS); do \
@@ -102,21 +109,29 @@ cppcheck: config.status
 	done; \
 	exit $$rval
 
+splint: config.status
+	rval=0; \
+	for d in $(SUBDIRS); do \
+	    echo splinting $$d; \
+	    (cd $$d && exec $(MAKE) SPLINT_OPTS="$(SPLINT_OPTS)" $@) || rval=`expr $$rval + $$?`; \
+	done; \
+	exit $$rval
+
 install-dirs install-binaries install-includes install-plugin: config.status pre-install
 	for d in $(SUBDIRS); do \
-	    (cd $$d && exec $(MAKE) $@) && continue; \
+	    (cd $$d && exec $(MAKE) "INSTALL_OWNER=$(INSTALL_OWNER)" $@) && continue; \
 	    exit $$?; \
 	done
 
 install-doc: config.status ChangeLog
 	for d in $(SUBDIRS); do \
-	    (cd $$d && exec $(MAKE) $@) && continue; \
+	    (cd $$d && exec $(MAKE) "INSTALL_OWNER=$(INSTALL_OWNER)" $@) && continue; \
 	    exit $$?; \
 	done
 
 install: config.status ChangeLog pre-install install-nls
 	for d in $(SUBDIRS); do \
-	    (cd $$d && exec $(MAKE) $@) && continue; \
+	    (cd $$d && exec $(MAKE) "INSTALL_OWNER=$(INSTALL_OWNER)" $@) && continue; \
 	    exit $$?; \
 	done
 
@@ -133,26 +148,21 @@ uninstall-nls:
 	done
 
 siglist.c signame.c:
-	(cd compat && exec $(MAKE) $@)
+	(cd lib/util && exec $(MAKE) $@)
 
 depend: siglist.c signame.c
-	@if test "$(srcdir)" != "."; then \
-	    echo "make depend only supported in the source directory"; \
-	    exit 1; \
-	fi; \
-	$(srcdir)/mkdep.pl $(srcdir)/common/Makefile.in \
-	    $(srcdir)/compat/Makefile.in $(srcdir)/plugins/sample/Makefile.in \
-	    $(srcdir)/plugins/group_file/Makefile.in \
-	    $(srcdir)/plugins/sudoers/Makefile.in \
-	    $(srcdir)/plugins/system_group/Makefile.in \
-	    $(srcdir)/src/Makefile.in $(srcdir)/zlib/Makefile.in; \
-	./config.status --file $(srcdir)/common/Makefile \
-	    --file $(srcdir)/compat/Makefile \
-	    --file $(srcdir)/plugins/sample/Makefile \
-	    --file $(srcdir)/plugins/group_file/Makefile \
-	    --file $(srcdir)/plugins/sudoers/Makefile \
-	    --file $(srcdir)/plugins/system_group/Makefile \
-	    --file $(srcdir)/src/Makefile --file $(srcdir)/zlib/Makefile
+	$(top_srcdir)/mkdep.pl --builddir=`pwd` --srcdir=$(top_srcdir) \
+	    lib/util/Makefile.in lib/zlib/Makefile.in \
+	    plugins/group_file/Makefile.in plugins/sample/Makefile.in \
+	    plugins/sudoers/Makefile.in plugins/system_group/Makefile.in \
+	    src/Makefile.in && \
+	$(top_builddir)/config.status --file $(top_builddir)/lib/util/Makefile \
+	    --file $(top_builddir)/plugins/sample/Makefile \
+	    --file $(top_builddir)/plugins/group_file/Makefile \
+	    --file $(top_builddir)/plugins/sudoers/Makefile \
+	    --file $(top_builddir)/plugins/system_group/Makefile \
+	    --file $(top_builddir)/src/Makefile \
+	    --file $(top_builddir)/lib/zlib/Makefile
 
 ChangeLog:
 	if test -d $(srcdir)/.hg && cd $(srcdir); then \
@@ -178,7 +188,7 @@ Makefile: $(srcdir)/Makefile.in
 sync-po: rsync-po compile-po
 
 rsync-po:
-	rsync -Lrtvz  translationproject.org::tp/latest/sudo/ src/po/
+	rsync -Lrtvz  translationproject.org::tp/latest/sudo/ po/
 	rsync -Lrtvz  translationproject.org::tp/latest/sudoers/ plugins/sudoers/po/
 
 update-pot:
@@ -188,10 +198,11 @@ update-pot:
 		echo "Updating $$pot"; \
 		domain=`basename $$pot .pot`; \
 		case "$$domain" in \
-		    sudo) tmpfiles=; cfiles="src/*c common/*c compat/*c";; \
+		    sudo) tmpfiles=; cfiles="src/*c lib/*/*c";; \
 		    sudoers) \
-			echo "syntax error" > confstr.sh; \
-			sed -n -e 's/^badpass_message="/gettext "/p' \
+			echo "gettext \"syntax error\"" > confstr.sh; \
+			$(SED) -n 's/^.*--with-passprompt=\(.*\)$$/gettext \"\1\"/p' mkpkg | sort -u >> confstr.sh; \
+			$(SED) -n -e 's/^badpass_message="/gettext "/p' \
 			    -e 's/^passprompt="/gettext "/p' \
 			    -e 's/^mailsub="/gettext "/p' configure.ac \
 			    >> confstr.sh; \
@@ -205,7 +216,7 @@ update-pot:
 		    rm -f $$pot.tmp; \
 		else \
 		    printf '/^#$$/+1,$$d\nw\nq\n' | ed - $$pot; \
-		    sed '1,/^#$$/d' $$pot.tmp >> $$pot; \
+		    $(SED) '1,/^#$$/d' $$pot.tmp >> $$pot; \
 		    rm -f $$pot.tmp; \
 		fi; \
 	    done; \
@@ -235,24 +246,23 @@ compile-po:
 		    POFILES="$$POFILES $$po"; \
 		done; \
 	    done; \
-	    echo "all: `echo $$POFILES | sed 's/\.po/.mo/g'`" >> Makefile.$$$$; \
+	    echo "all: `echo $$POFILES | $(SED) 's/\.po/.mo/g'`" >> Makefile.$$$$; \
 	    echo "" >> Makefile.$$$$; \
 	    for po in $$POFILES; do \
-		mo=`echo $$po | sed 's/po$$/mo/'`; \
+		mo=`echo $$po | $(SED) 's/po$$/mo/'`; \
 		echo "$$mo: $$po" >> Makefile.$$$$; \
 		echo "	$(MSGFMT) --statistics -c -o $$mo $$po" >> Makefile.$$$$; \
 	    done; \
-	    make -f Makefile.$$$$; \
+	    $(MAKE) -f Makefile.$$$$; \
 	    rm -f Makefile.$$$$; \
 	fi
 
 install-nls:
 	@if test "$(NLS)" = "enabled"; then \
-	    cd $(top_srcdir); \
 	    for pot in $(POTFILES); do \
-		podir=`dirname $$pot`; \
+		podir=`dirname $(top_srcdir)/$$pot`; \
 		domain=`basename $$pot .pot`; \
-		SUDO_LINGUAS=$${LINGUAS-"`echo $$podir/*.mo|sed 's:'$$podir'/\([^ ]*\).mo:\1:g'`"}; \
+		SUDO_LINGUAS=$${LINGUAS-"`echo $$podir/*.mo | $(SED) 's:'$$podir'/\([^ ]*\).mo:\1:g'`"}; \
 		echo $(ECHO_N) "Installing $$domain message catalogs:$(ECHO_C)"; \
 		for lang in $$SUDO_LINGUAS; do \
 		    test -s $$podir/$$lang.mo || continue; \
@@ -263,14 +273,14 @@ install-nls:
 			    ln -s $$lang $(DESTDIR)$(localedir)/$$lang$(LOCALEDIR_SUFFIX); \
 			fi; \
 		    fi; \
-		    $(INSTALL) -O $(install_uid) -G $(install_gid) -m 0644 $$podir/$$lang.mo $(DESTDIR)$(localedir)/$$lang/LC_MESSAGES/$$domain.mo; \
+		    $(INSTALL) $(INSTALL_OWNER) -m 0644 $$podir/$$lang.mo $(DESTDIR)$(localedir)/$$lang/LC_MESSAGES/$$domain.mo; \
 		done; \
 		echo ""; \
 	    done; \
 	fi
 
 check-dist: update-pot compile-po
-	@if [ -d .hg ]; then \
+	@if test -d $(srcdir)/.hg && cd $(srcdir); then \
 	    if test `hg stat -am | wc -l` -ne 0; then \
 		echo "Uncommitted changes" 1>&2; \
 		hg stat -am 1>&2; \
@@ -281,18 +291,20 @@ check-dist: update-pot compile-po
 dist: check-dist force-dist
 
 force-dist: ChangeLog $(srcdir)/MANIFEST
+	cd $(top_srcdir) && \
 	pax -w -x ustar -s '/^/$(PACKAGE_TARNAME)-$(VERSION)\//' \
 	    -f ../$(PACKAGE_TARNAME)-$(VERSION).tar \
-	    `sed 's/[ 	].*//' $(srcdir)/MANIFEST`
-	gzip -9f ../$(PACKAGE_TARNAME)-$(VERSION).tar
+	    `$(SED) 's/[ 	].*//' $(srcdir)/MANIFEST` && \
+	gzip -9f ../$(PACKAGE_TARNAME)-$(VERSION).tar && \
 	ls -l ../$(PACKAGE_TARNAME)-$(VERSION).tar.gz
 
-package: sudo.pp
+package: $(srcdir)/sudo.pp
 	DESTDIR=`cd $(top_builddir) && pwd`/destdir; rm -rf $$DESTDIR; \
-	$(MAKE) install DESTDIR=$$DESTDIR && \
+	$(MAKE) install INSTALL_OWNER= DESTDIR=$$DESTDIR && \
 	$(SHELL) $(srcdir)/pp $(PPFLAGS) \
 	    --destdir=$$DESTDIR \
 	    $(srcdir)/sudo.pp \
+	    prefix=$(prefix) \
 	    bindir=$(bindir) \
 	    sbindir=$(sbindir) \
 	    libexecdir=$(libexecdir) \
@@ -302,6 +314,7 @@ package: sudo.pp
 	    mandir=$(mandir) \
 	    localedir=$(localedir) \
 	    docdir=$(docdir) \
+	    exampledir=$(exampledir) \
 	    sysconfdir=$(sysconfdir) \
 	    sudoersdir=$(sudoersdir) \
 	    sudoers_uid=$(sudoers_uid) \
@@ -321,8 +334,8 @@ distclean: config.status
 	for d in $(SUBDIRS) $(SAMPLES); do \
 	    (cd $$d && exec $(MAKE) $@); \
 	done
-	-rm -rf Makefile pathnames.h config.h config.status config.cache \
-		config.log libtool stamp-* autom4te.cache
+	-rm -rf autom4te.cache config.cache config.h config.log config.status \
+	    init.d/*.sh init.d/sudo.conf libtool Makefile pathnames.h stamp-*
 
 cleandir: distclean
 
